# Generated by Django 3.1.3 on 2020-11-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('num_course_enrolled', models.IntegerField(default=0)),
                ('num_course_completed', models.IntegerField(default=0)),
            ],
        ),
    ]
