# Generated by Django 3.1.3 on 2020-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default=1234, max_length=16),
            preserve_default=False,
        ),
    ]
