# Generated by Django 3.1.3 on 2020-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num_course_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_course_taken',
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
