# Generated by Django 3.1.3 on 2020-11-17 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iros2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('abstract', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('pdf_file', models.FileField(upload_to='blog_file')),
                ('blog_type', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('abstract', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('pdf_file', models.FileField(upload_to='blog_file')),
                ('blog_type', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='techspresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('abstract', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('pdf_file', models.FileField(upload_to='blog_file')),
                ('blog_type', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
