# Generated by Django 3.1.3 on 2020-11-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iros2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('md_file', models.FileField(upload_to='blog_file')),
                ('blog_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('md_file', models.FileField(upload_to='blog_file')),
                ('blog_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='techspresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('md_file', models.FileField(upload_to='blog_file')),
                ('blog_type', models.CharField(max_length=200)),
            ],
        ),
    ]
