# Generated by Django 3.1.3 on 2020-11-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iros2020',
            name='abstract',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='techspresso',
            name='abstract',
            field=models.CharField(max_length=500),
        ),
    ]
