# Generated by Django 3.1.3 on 2020-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('IROS2020', 'IROS2020'), ('Research', 'Research'), ('Techspresso', 'Techspresso')], max_length=200),
        ),
    ]
