# Generated by Django 3.1.3 on 2020-12-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=20, unique=True)),
                ('course_descr', models.TextField()),
                ('no_modules', models.IntegerField()),
                ('course_fee', models.FloatField()),
                ('course_cover_img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('moduel_no', models.IntegerField()),
                ('no_text', models.IntegerField()),
                ('no_videos', models.IntegerField()),
                ('no_assignment', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_no', models.IntegerField()),
                ('content_type', models.CharField(choices=[('Text', 'Text'), ('Video', 'Video'), ('Assignment', 'Assignment')], max_length=20)),
                ('content_link', models.CharField(max_length=200)),
                ('time_req', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
        ),
    ]
