# Generated by Django 3.1.3 on 2020-12-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_desc',
            field=models.TextField(default='No Desc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(choices=[('Computer Vision', 'Computer Vision'), ('Controls', 'Controls'), ('Kinematics', 'Kinematics')], max_length=20, unique=True),
        ),
    ]
